#!/usr/bin/env python3
#
# Do not edit this file
#
# This file was generated using the script 'generate_commands_py.py'
#

from distutils.core import setup

setup(
    name="Skydel SDX",
    version="43",
    packages=["skydelsdx"],
    license="Commercial License",
    long_description="Skydel python module for remote commands"
)